name: docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get app meta
        id: app-meta
        run: |
          echo "name=react-nginx-app" >> "$GITHUB_OUTPUT"
          echo "version=0.0.0" >> "$GITHUB_OUTPUT"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: > 
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ needs.app-meta.outputs.name }}:${{ needs.app-meta.outputs.version }},
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ needs.app-meta.outputs.name }}:latest
          build-args: |
            APP_VERSION=${{ vars.APP_VERSION }}