name: docker

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test --run
  docker:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
      - name: Get app meta
        id: app-meta
        run: |
          echo "name=$(jq -r .name package.json)" >> "$GITHUB_OUTPUT"
          echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: >
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.app-meta.outputs.name }}:${{ steps.app-meta.outputs.version }},
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.app-meta.outputs.name }}:latest
          build-args: |
            APP_VERSION=${{ vars.APP_VERSION }}
